### ISSUE TITLE
Ошибка в коде

### ISSUE THREAD

**Issue by SobolevWladimir** [cloudpayments/SDK-Android#2]
У вас Ошибка в коде.. 
 файл SDK-Android/sdk/src/main/java/ru/cloudpayments/sdk/cp_card/CPCard.java
строка 135. 

`/**
     * Валидация даты
     * @return
     */
    public boolean isValidExpDate() {
        return isValidNumber(expDate);
    }`
 вместо возвращаемого значения  isValidNumber() должен быть isValidExpDate

**Comment by a-ignatov-cp** [comment]
Действительно, ошибка есть.
Исправили, используйте версию 1.0.2
Спасибо!
