### ISSUE TITLE
POST_BACK_URL

### ISSUE THREAD

**Issue by AyupovIlgam** [cloudpayments/SDK-Android#4]
![image](https://user-images.githubusercontent.com/10988134/86120723-a3bcc500-baf6-11ea-8235-18df1a86748a.png)

При вызове формы для подтверждения 3DS нет возможности указать POST_BACK_URL.
Это сделано намерено?

**Comment by a-ignatov-cp** [comment]
Добрый день! Все верно, это сделано намерено, этот URL передается 3DS форме банка, для обработки ответа после ее прохождения. Если Вам необходимо передать какую-то информацию о проведении платежа на Ваш сервер, обратите внимание на схему проведения платежа, все запросы к нашему серверу необходимо выполнять через Ваш сервер, в папке api есть пример реализации подобного небольшого API, в нем Вы можете добавить вызовы своих методов.
